name: MFC Paint App CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Build MFC Paint App
        run: |
          cd MFC-Paint-App
          msbuild MFCPaintApp.sln /p:Configuration=Release /p:Platform="x64"

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MFC-Paint-Build
          path: '**\Release\*.exe'
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
          files: '**/Release/*.exe'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
